# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0013_clanuserpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicuserpointsubmission',
            name='isDB',
            field=models.BooleanField(default=False),
        ),
    ]
